package com.tark.ports.outbound.react

import cats.effect.Sync
import com.tark.domain.tool.{Tool, ToolCallRequest}
import com.tark.domain.Interaction
import com.tark.ports.outbound.backend.LlmClient

/**
 * Structured response for a hybrid ReAct turn.
 * @param thought The Chain-of-Thought reasoning generated by the model's text content.
 * @param action Either Left(finalAnswer) when converged, or Right(ToolCallRequest) when executing a tool.
 */
case class ReActResponse(
                         thought: String,
                         action: Either[String, ToolCallRequest]
                         )

/**
 * Typeclass for LLM client integration in a ReAct context.
 * Natively extracts both text reasoning (thoughts) and native tool invocations.
 */
trait ReActLlmClient[F[_]] {
  def getCompletion(
    prompt: String,
    history: List[Interaction],
    systemPrompt: String,
    tools: List[Tool]
  ): F[Either[String, ReActResponse]]
}

trait ReActToolPolicy {
  def choose(calls: List[ToolCallRequest]): Either[String, ToolCallRequest]
}

object ReActToolPolicy {
  val firstToolWins: ReActToolPolicy =
    (calls: List[ToolCallRequest]) =>
      calls.headOption.toRight("No tool calls returned")
}

object ReActLlmClient {

  /**
   * Generic adapter that converts any standard LlmClient[F] into a ReActLlmClient[F].
   *
   * Laws for the default derivation:
   * - text completions become final ReAct answers;
   * - non-empty tool-call lists select the first call for the next ReAct step;
   * - empty tool-call lists are treated as an adapter error.
   */
  def fromLlmClient[F[_]: Sync](policy: ReActToolPolicy)(using client: LlmClient[F]): ReActLlmClient[F] =
    new ReActLlmClient[F] {
      override def getCompletion(
        prompt: String,
        history: List[Interaction],
        systemPrompt: String,
        tools: List[Tool]
      ): F[Either[String, ReActResponse]] = {
        val F = summon[Sync[F]]
        F.map(client.getCompletion(prompt, history, systemPrompt, tools)) {
          case Left(text) =>
            Right(ReActResponse(text, Left(text)))
          case Right(toolCalls) =>
            policy.choose(toolCalls).map { toolCall =>
              ReActResponse("Executing tool call...", Right(toolCall))
            }
        }
      }
    }

  given defaultReActLlmClient[F[_]: Sync](using client: LlmClient[F]): ReActLlmClient[F] =
    fromLlmClient(ReActToolPolicy.firstToolWins)
}
